POST http://localhost:8080/finance/user HTTP/1.1
Content-Type: application/json

{
    "id" : 1,
    "invDt": "2022-01-01",
    "financeType": "INVESTMENT",
    "tag": "salary",
    "amt": 5000.0,
    "userId" : 2
}
###
POST http://localhost:8080/finance/user HTTP/1.1
Content-Type: application/json

{
    "id" : 1,
    "invDt": "2022-01-01",
    "financeType": "INCOME",
    "tag": "salary",
    "amt": 5000.0,
    "userId" : 1
}

### update a Finance tag
POST http://localhost:8080/finance/user
Content-Type: application/json

{
  "id": 1,
  "financeType": "INCOME",
  "tag": "salary",
  "invDt": "2023-12-23",
  "amt": 12300
}

### All the Finances
GET http://localhost:8080/finance/user-finances

###
GET http://localhost:8080/finance/user-finances?userDto.id=1



### Specific Finance 
GET http://localhost:8080/finance/user/9

###
GET http://localhost:8080/budget/income/salary/sum

###
GET http://localhost:8080/finance/total-income

###
GET http://localhost:8080/finance/total-expenses

###
DELETE http://localhost:8080/finance/delete/2

