POST http://localhost:8080/budget/
Content-Type: application/json

{
  "category": "Food",
  "amount": 1000.00,
  "recurring": true,
  "startDate": "2023-05-17",
  "endDate": "2023-05-31",
  "user": {
    "id": 2
  }
}

###
POST http://localhost:8080/budget/user
Content-Type: application/json

{
  "category": "Food",
  "amount": 1000.00,
  "recurring": true,
  "startDate": "2023-05-17",
  "endDate": "2023-05-31",
    "id": 1

}

###
POST http://localhost:8080/budget/user/
Content-Type: application/json

{
  "category": "Food",
  "amount": 1000.00,
  "recurring": true,
  "startDate": "2023-05-17",
  "endDate": "2023-05-31",
  "user": {
    "id": 1,
    "name": "yellow",
    "email": "testing4@gmail.com"
  }
}