
###
POST http://localhost:8080/finance/user
Content-Type: application/json

{
  "userId": 1,
  "id": 8,
  "financeType": "EXPENSES",
  "tag": "investment",
  "invDt": "2023-12-23",
  "amt": 2300
}

###
POST http://localhost:8080/finance/user
Content-Type: application/json

{
  "userId": 1,
  "id": 8,
  "financeType": "INCOME",
  "tag": "salary",
  "invDt": "2023-12-23",
  "amt": 12300
}
###
GET http://localhost:8080/finance/




### Create New Account
POST http://localhost:8080/finance/user
content-type: application/json

{
    "id":1,
    "financetye" : "zwr", 
     "tag":"investment",
    "invDt" : "2020-01-01",
    "amt" : 98
}

### Create New Invoice with Customer
POST http://localhost:8080/finance/user/ HTTP/1.1 
content-type: application/json

{   "id":1,
    "financetype":"expense",
    "tag" : "Paytm", 
    "invDt" : "2020-01-01",
    "amt" : 1800,
    "customerId" : 1
}


### Get All Invoices
GET http://localhost:8080/finance/
content-type: application/json

{
    "financetype":"expense",
    "tag" : "Paytm", 
    "invDt" : "2020-01-01",
    "amt" : 1800,
    "customerId" : 1
}

### Delete Invoice By Id
DELETE http://localhost:8080/finance/users

### Invoice By Id
GET http://localhost:8080/finance/7

### Create New Account

PUT http://localhost:8080/finance/ HTTP/1.1 
content-type: application/json

{
    "id" : 10, 
    "client" : "ooo", 
    "invDt" : "1990-01-01",
    "amt" : 70000
}

### List All Customer Invoices
GET http://localhost:8080/finance/users/17

