
### Add a finance info 
POST http://localhost:8080/finance/user
Content-Type: application/json

{
  "userId": 1,
  "id": 8,
  "financeType": "EXPENSES",
  "tag": "investment",
  "invDt": "2023-12-23",
  "amt": 2300
}


### update a Finance tag
POST http://localhost:8080/finance/user
Content-Type: application/json

{
  "userId": 1,
  "id": 8,
  "financeType": "INCOME",
  "tag": "salary",
  "invDt": "2023-12-23",
  "amt": 12300
}

### All the Finances
GET http://localhost:8080/finance/



### Specific Finance 
GET http://localhost:8080/finance/user/11

