POST http://localhost:8080/users/register
Content-Type: application/json

{
"name":"gettok",
"email": "user3id1@gmail.com",
"password": "yello"
}

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
"email": "getwell1",
"password": "jla;f;a"
}
###
DELETE http://localhost:8080/users/all

